### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by yoofibiney** [ernest19/Geospatial_Developers#1]
hello Ernest,
After downloading the zip file of the dataset, there seems to be a problem with the extracting the contents. A pop of arises saying the archive is an unknown format or damaged...could you look into it
Thanks

**Comment by ernest19** [comment]
> hello Ernest, After downloading the zip file of the dataset, there seems to be a problem with the extracting the contents. A pop of arises saying the archive is an unknown format or damaged...could you look into it Thanks

Hello Yoofi , please check on the telegram page .i  post it there also.
