### ISSUE TITLE
Issue with adding base map

### ISSUE THREAD

**Issue by danielq02** [ernest19/Geospatial_Developers#2]
After installing the QuickMapServices I applied the Google Hybrid option.
But the Google hybrid layer is not showing as you did.

**Comment by ernest19** [comment]
Helloo Daniel , usual when it happens like that, kindly check if your internet is connected .

**Comment by ernest19** [comment]
> After installing the QuickMapServices I applied the Google Hybrid option. But the Google hybrid layer is not showing as you did.

Helloo Daniel , usual when it happens like that, kindly check if your internet is connected .
