### ISSUE TITLE
Ebenezer Bamidele - Geoportal Assignment

### ISSUE THREAD

**Issue by ebene06** [ernest19/Geospatial_Developers#5]
[Ebenezer_Bamidele_Geoportal_Assignment.zip](https://github.com/ernest19/Geospatial_Developers/files/9618360/Ebenezer_Bamidele_Geoportal_Assignment.zip)
Good day Ernest,
Please I have uploaded my Geoportal assignment for review and correction

**Comment by ernest19** [comment]
Well Done Ebenezer.  that is a good attempt. there were few issues
